// export { setup as startSetup } from './start'
export { setup as q1Setup } from './q1'
export { setup as q2Setup } from './q2'
export { setup as q2EndSetup } from './q2_end'
export { setup as q3Setup } from './q3'
export { setup as q6Setup } from './q6'
export { setup as flipYsetup } from './flipY'
export { setup as scrollCoverReverseSetup } from './scrollCoverReverse'
export { setup as zoomCoverReverseSetup } from './zoomCoverReverse'
export { setup as clipPathSetup } from './clipPath'
export { setup as rotateSetup } from './rotate'
export { setup as sliceXSetup } from './sliceX'
